### ISSUE TITLE
MonacoEditorの自動レイアウトとReactResizableがうまく動かない

### ISSUE THREAD

**Issue by izszzz** [izszzz/stave#4]
Mainがflex
ExplorerがReactResizable
TabEditorが自動レイアウト

1. Editor Stack
```css
.Main{
  display: flex;
}
.Explorer{
}
TabEditor {
  flex: 1;
}
// automaticLayout true
```

2. Editor Stack
```css
.Main{
  display: flex;
}
.Explorer{
}
TabEditor {
  width: 100%;
}
// automaticLayout true
```
